flags: {}
extra-package-dbs: []
packages:
- '.'
- 'yesod-auth-token'
extra-deps:
- hoauth2-0.5.0.1
- load-env-0.1.1
- persistent-sqlite-2.2
- text-1.2.2.0
- yaml-0.8.15.2
- yesod-auth-oauth2-0.1.8
- yesod-paginator-0.10.0
resolver: nightly-2016-01-02
